#!/bin/bash
#SBATCH --job-name=eurlex4k            # Job name
#SBATCH --output=output.%A_%a.txt         # Standard output and error log
#SBATCH --nodes=1                         # Run all processes on a single node
#SBATCH --ntasks=1                        # Run on a single CPU
#SBATCH --mem=64G                        # Total RAM to be used
#SBATCH --cpus-per-task=128               # Number of CPU cores
#SBATCH -p cscc-cpu-p                     # Use the CPU partition
#SBATCH --time=3:00:00                   # Time needed for the experiment
#SBATCH --qos=cscc-cpu-qos

hostname

# python3 main.py --data_name eurlex4k_zs \
#     --model_name tree \
#     --training_file /nfs-stor/linh.vu/EURLEX-4K/zeroshot/EURLEX-4K_tfidf_train.svm \
#     --test_file /nfs-stor/linh.vu/EURLEX-4K/zeroshot/EURLEX-4K_tfidf_test.svm \
#     --linear --linear_technique tree \
#     --result_dir /nfs-stor/linh.vu/runs \
#     --data_format svm

python3 main.py --data_name eurlex4k_zs_pecos \
    --model_name tree \
    --training_file /nfs-stor/linh.vu/EURLEX-4K/eurlex4k_tfidf_train_ext_pecos.svm\
    --test_file /nfs-stor/linh.vu/EURLEX-4K/eurlex4k_tfidf_test_ext_pecos.svm \
    --linear --linear_technique tree \
    --result_dir /nfs-stor/linh.vu/runs \
    --data_format svm
