#!/bin/bash
#SBATCH --job-name=dexmlGeneration         # Job name
#SBATCH --output=output.%A_%a.txt   # Standard output and error log
#SBATCH --nodes=1                   # Run all processes on a single node  
#SBATCH --ntasks=1                  # Run on a single CPU
#SBATCH --mem=128G                   # Total RAM to be used
#SBATCH --cpus-per-task=64          # Number of CPU cores
#SBATCH --gres=gpu:1                # Number of GPUs (per node)
#SBATCH -p cscc-gpu-p               # Use the gpu partition
#SBATCH --exclude=gpu-50,gpu-56,gpu-51,gpu-52,gpu-53,gpu-54,gpu-55
#SBATCH --time=00:30:00             # Specify the time needed for your experiment
#SBATCH --qos=cscc-gpu-qos          # To enable the use of up to 8 GPUs

python3 "/nfs-stor/linh.vu/dataprep_files/3_2.text_to_dexml.py" --config "/nfs-stor/linh.vu/dataprep_files/config_eurlex4k.json"